name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [fmt, clippy, test]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          key: ${{ matrix.os }}-${{ matrix.task }}

      - name: fmt-check
        if: matrix.task == 'fmt'
        run: cargo fmt --check

      - name: clippy
        if: matrix.task == 'clippy'
        run: cargo clippy --all-targets --locked -- -D warnings

      - name: test
        if: matrix.task == 'test'
        run: cargo test --locked
